traits:
  asdf: true

git_options:
  submodules:
    include_match: ^.*$

scripts:
  api-build:
    exclusive_executor_resource: madek-api-build-uberjar
    body: |
      #/bin/env bash
      set -euo pipefail
      cd $API_DIR
      ./bin/build
