scripts:
  configure-rspec-database:
    start_when:
      datalayer-configure-rails-db:
        script_key: datalayer-configure-rails-db 
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cp $DATALAYER_DIR/config/database.yml spec/config/database.yml

  test:
    start_when:
      configure-rspec-database passed:
        script_key: configure-rspec-database


