AllCops:
  Exclude:
    - 'datalayer/**/*'

Style/Documentation:
  Exclude:
    - 'spec/config/rails.rb'

Style/FileName:
  Exclude:
    - 'spec/resources/media-entry_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'Gemfile'

Style/FileName:
  Exclude:
    - 'spec/authentication/basic-auth_spec.rb'
    - 'spec/authentication/session-auth_spec.rb'
    - 'spec/resources/media-entry/meta-data_spec.rb'
    - 'spec/resources/media-entry_spec.rb'
    - 'spec/resources/media_entries/index-order-by_spec.rb'
    - 'spec/resources/meta-data/meta-datum-text_spec.rb'

Style/RescueModifier:
  Exclude:
    - 'spec/authentication/session-auth_spec.rb'
