jobs:

  build-uberjar:
    name: Build uberjar
    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
    context:
      include: cider-ci/context-components/uberjar.yml

  rspec-tests:
    name: "RSpec Tests"
    context:
      include: cider-ci/context-components/rspec-tests.yml
    depends_on: &UBERJAR
      rspec tests: { type: job, job_key: build-uberjar, states: [passed]}
    run_when: *UBERJAR

  lint:
    name: "Linting"
    description: |
      Code checks: static checks and metrics: complexity, duplication, and format,
      also other consistency checks.
    priority: 3
    run_when: *DEFAULT_TRIGGERS
    context:
      task_defaults:
        include: [cider-ci/task-components/env.yml]
        environment_variables:
          GIT_LINEAR_HISTORY_CHECK_START_SHA: d9b3e6a1d0397d7294e85a4a189d86aa843f1dfc
      contexts:
        include:
          - path: cider-ci/context-components/lint/git-lint.yml
            submodule: [datalayer]
          - path: cider-ci/context-components/lint/rspec-lint.yml
            submodule: [datalayer]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# META JOBS (only depend on other jobs)                                           #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  all-tests:
    name: All Tests
    description: |
      This job depends on all unit jobs that need to pass.
      It is depended upon by the super-project!
      *Note that there still be more requirements for actually pushing to `origin`,
      look in job **"Good to Merge"**!*
    priority: 999 # "empty" job = high priority
    depends_on: &ALL_TEST_DEPENDS
      rspec tests: { type: job, job_key: rspec-tests, states: [passed]}
      all-tests of the datalayer: {job_key: all-tests, type: job, submodule: [datalayer], states: [passed]}
    run_when: *ALL_TEST_DEPENDS
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# GITHUB BRANCH PROTECTION                                                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  good-to-merge:
    name: "⚑ Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "delivery" job = high priority
    context:
      include:
        - path: cider-ci/context-components/env.yml
        - submodule: [datalayer]
          path: cider-ci/context-components/merge-checks.yml
    depends_on:
      all-tests: {job_key: all-tests, type: job, states: [passed]}
      good to merge of the datalayer: {job_key: good-to-merge, type: job, submodule: [datalayer], states: [passed]}
