jobs:

  all-tests:
    run-on:
    - type: branch
      include-match: ^.*$
    name: All Tests
    depends-on:
    - type: job
      job: docs
      states: [passed]
    - type: job
      job: specs
      states: [passed]
    - type: job
      job: tests
      states: [passed]
      submodule: ['docs_source']

    task: echo 'Yay, all dependencies have passed!'

  docs:
    name: Docs
    run-on:
    - type: branch
      include-match: ^.*$
    _cider-ci_include: cider-ci/jobs/docs.yml
    traits: [bash, ruby, git]
    git-options:
      submodules:
        clone: True
        timeout: 60
    task: |
      set -eux


  specs:
    name: Specs
    run-on:
    - type: branch
      include-match: ^.*$
    depends-on:
    - type: job
      job: tests
      submodule: ['datalayer']
      states: [passed]
    _cider-ci_include: cider-ci/jobs/specs.yml
