# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem 'addressable'
gem 'bcrypt'
gem 'capybara'
gem 'chronic_duration'
gem 'cider_ci-open_session', '>= 1.0.0', '< 2.0.0'
gem 'factory_girl', group: [:test, :development]
gem 'faker'
gem 'faraday'
gem 'git'
# gem 'json_roa-client', path: '/Users/thomas/Programming/JSON-ROA/ruby_client' # '= 2.0.0.pre.beta.2'
gem 'json_roa-client', '=2.0.0.pre.beta.5'
gem 'pg'
gem 'pg_tasks', '>= 1.3.1', '< 2.0.0'
gem 'pry'
gem 'rails', '~> 4.2'
gem 'rails_config', git: 'https://github.com/DrTom/rails_config.git', ref: 'master'
gem 'rest-client'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'timecop'
gem 'uuidtools'
