madek_master_secret: 'secret'

madek_api_session_enabled: true
madek_session_cookie_name: 'madek-session'
madek_session_validity_duration: 7 days


database: {}

services:

  api:

    cors_enabled: false

    http:

      host: localhost
      port: 3100
      context: ""
      sub_context: /api
      ssl: false



