madek_master_secret: 'secret'

madek_session_cookie_name: 'madek-session'

database: {}

services:

  api:

    http:

      host: localhost
      port: 3100
      context: ""
      sub_context: /api
      ssl: false



