default_storage_dir: {{CIDER_CI_WORKING_DIR}}/tmp/storage

madek_master_secret: secret
madek_session_cookie_name: madek-session

database:
  adapter: "postgresql"
  classname: "org.postgresl.Driver"
  subname: '//localhost:REPLACE_WITH_PGPORT/{{DATABASE}}'
  subprotocol: "postgresql"
  user: REPLACE_WITH_PGUSER
  password: REPLACE_WITH_PGPASSWORD
  max_pool_size: 3

services:

  api:

    http:

      host: localhost
      port: {{API_HTTP_PORT}}
      context: ""
      sub_context: /api
      ssl: false


