- name: install service from template
  template:
    src: madek-api.service
    dest: /etc/systemd/system/madek-api.service
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes
  failed_when: false

- name: enable and (re)start api-service
  service:
    name: madek-api
    state: restarted
    enabled: true

- name: wait for service to start
  wait_for:
    port: "{{madek_api_port}}"
    delay: 5
    timeout: 60
